services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE: "/api"
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped
    profiles: ["production"]

  frontend-dev:
    build:
      context: ./frontend
      target: builder
    command: npm run dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    profiles: ["development"]
